simulation:
  host: "localhost"
  port: 64256
  home: "C:\\Users\\user\\Documents\\beamng-tech\\BeamNG.tech.v0.37.6.0"
  deterministic_fps: 60

vehicles:
  etk800:
    name: "etk_egovehicle"
    model: "etk800"
    license: "JULIAN"

  q8_andronisk:
    name: "q8_egovehicle"
    model: "q8_andronisk"
    license: "JULIAN"
    part_config: "main.pc"
