sensors:
  camera:
    name: "front_cam"
    enabled: true
    requested_update_time: 0.01
    is_using_shared_memory: true
    pos: [ 0, -1.3, 1.4 ]
    dir: [ 0, -1, 0 ]
    field_of_view_y: 90
    near_far_planes: [ 0.1, 1000 ]
    resolution: [ 640, 360 ]
    is_streaming: true
    is_render_colours: true

  lidar:
    name: "lidar1"
    enabled: true
    requested_update_time: 0.01
    is_using_shared_memory: true
    is_rotate_mode: false
    horizontal_angle: 170
    vertical_angle: 30
    vertical_resolution: 64
    density: 7
    frequency: 15
    max_distance: 100
    pos: [ 0, -0.35, 1.425 ]
    is_visualised: false

  radar:
    name: "radar1"
    enabled: true
    requested_update_time: 0.01
    pos: [ 0, -2.5, 0.5 ]
    dir: [ 0, -1, 0 ]
    up: [ 0, 0, 1 ]
    size: [ 200, 200 ]
    near_far_planes: [ 2, 120 ]
    field_of_view_y: 70
